# tensors in tensorflow comand mm
More specifically we are going to cover:
* intro to tensors
* getting info from tensors
* manipulating tensors
* tensors & numpy
* using @tf.function(a way to speed up your regular python function)
* using GPUs with tensorflow/TPUs
* Excercise

## Intro to tensors

In [2]:
# import tensorflow
import tensorflow as tf
tf.__version__

'2.11.0'

In [3]:
# create tensors with  tf.constant()
scalar=tf.constant(7)
scalar
# command+shift+space for docstring in colab

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check number of dimension in tensor
scalar.ndim

0

In [5]:
# create vector
vector=tf.constant([2,3,4])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [6]:
#  check dimension of vector
vector.ndim

1

In [7]:
# create matrix(has more than 1 dimension)
matrix=tf.constant([[3,2],
                    [5,6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [5, 6]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# lets create another matrix
another_matrix=tf.constant([[2.,3.],
                            [4.,5.3]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2. , 3. ],
       [4. , 5.3]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# lets create tensor
tensor=tf.constant([[[3,4],[5,5]]])
tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[3, 4],
        [5, 5]]], dtype=int32)>

In [12]:
tensor.ndim

3

# everyrhing even matrix are refered as tensors, matrix tensor same thing. 3d tensor or 2d tensor

What we heave created
* scalar: single constant number
* vector: number with direction (eg wind speed and direction)
* matrix: 2d array of numbers
* tensor: n-dimension array of numbers (can be 0-dim=tensor is a scalar, 1d-tensor is vector, 2d-tensor is matrix or more)

 ### creating tensors with `tf.Variable`

In [13]:
changable_tensor=tf.Variable([2,3])
unchangable_tensor=tf.constant([3,4])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [15]:
changable_tensor[0]=5

TypeError: ignored

In [16]:
changable_tensor[0].assign(55)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([55,  3], dtype=int32)>

In [17]:
unchangable_tensor[0].assign(46)

AttributeError: ignored

In [18]:
unchangable_tensor[0]=-35

TypeError: ignored

 ## always create `tf.conatant` if you really need it 

## create random tensor: use case for initializing model weight:  here we create pseud random using seed, they appear as random but really aren't because of seed they become same

In [19]:
tf.random.Generator.from_seed(101).uniform((2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.22709787, 0.49256873, 0.7682668 , 0.8009803 , 0.7784879 ],
       [0.7249299 , 0.89754343, 0.7963594 , 0.6212156 , 0.02030826]],
      dtype=float32)>

In [20]:
# create two same tandom tensor using seed
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal((2,2,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal((2,2,2))
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702],
         [ 0.07595026, -1.2573844 ]],
 
        [[-0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
 array([[[-0.7565803 , -0.06854702],
         [ 0.07595026, -1.2573844 ]],
 
        [[-0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=bool, numpy=
 array([[[ True,  True],
         [ True,  True]],
 
        [[ True,  True],
         [ True,  True]]])>)

In [21]:
tf.random.normal((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.51929754,  1.0671289 ,  0.43264177],
       [ 0.72132534,  0.75572145, -0.44528016]], dtype=float32)>

## suffle tenser: valuable when you want to suffle data so that inherient order doesnot effect learning

In [22]:
tf.random.set_seed(123)
not_suffled=tf.constant([[1,2,3],
                         [4,5,6],
                         [3,6,7]])
tf.random.shuffle(not_suffled, seed=123)
# suffles along first dimension making column intact

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 6, 7],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [23]:
not_suffled_random=tf.random.normal((3,2,2))

In [24]:
not_suffled_random

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[-0.8980837 , -1.8259144 ],
        [-0.44441807, -1.4882947 ]],

       [[-0.7855463 ,  0.19619656],
        [ 0.17604655, -1.5252506 ]],

       [[ 0.635294  ,  0.66812044],
        [ 1.4230527 ,  0.04561644]]], dtype=float32)>

In [25]:
tf.random.shuffle(not_suffled_random, seed=123)

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 0.635294  ,  0.66812044],
        [ 1.4230527 ,  0.04561644]],

       [[-0.7855463 ,  0.19619656],
        [ 0.17604655, -1.5252506 ]],

       [[-0.8980837 , -1.8259144 ],
        [-0.44441807, -1.4882947 ]]], dtype=float32)>

> If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence. we need to set both seed to have suffle same order(different than original tensor) no matter how many time you run it.

In [26]:
tf.random.set_seed(123)# globel level random seed
not_suffled=tf.constant([[1,2,3],
                         [4,5,6],
                         [3,6,7]])
tf.random.shuffle(not_suffled, seed=125)# operation level random seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [3, 6, 7]], dtype=int32)>

>> to make reproducible experiement, you want to suffle data in similar order, and have similar pattern(weight) for each new experiment. 
>because neural network initialize different weight in each experiment, to reproduce same result, initialize with seed.

# 14

In [30]:
#  create tensor of all ones
tf.ones(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [31]:
# create tensor of all zeros
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### turn numpy array into tensor
tensor runs on GPU(much faster for numerical computing than numpy) else both are same

In [38]:
import numpy as np
numpy_A=np.arange(1,6, dtype=np.int32)
tensorflow_tensor=tf.Variable(numpy_A, dtype=tf.float16)
tensorflow_tensor, numpy_A
#  X=tf.constant(some_matrix) # capital X for matrix or tensor
#  y=tf.constant(vector) # non-capital y for vector

(<tf.Variable 'Variable:0' shape=(5,) dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>,
 array([1, 2, 3, 4, 5], dtype=int32))

In [44]:
import numpy as np
numpy_A=np.arange(1,25, dtype=np.int32)
tf.constant(numpy_A, shape=(2,3,4)), tf.Variable(numpy_A) 
# shape=(24,) is vector

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [45]:
tf.constant(numpy_A, shape=(2,3,4)).ndim

3

In [46]:
tf.constant(numpy_A, shape=(2,12))

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

## getting information from your tensor(tensor attributes)
* shape
* rank 
* axis or dimension
* size


In [58]:
# create rank 4 tensor(with 4 dimensions)
rank_4_tensor=tf.random.uniform([2,3,3,3])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0.48962688, 0.5857923 , 0.36451697],
         [0.6550509 , 0.9075084 , 0.37557673],
         [0.6882372 , 0.25384045, 0.49978244]],

        [[0.5126076 , 0.7279091 , 0.58709204],
         [0.9021536 , 0.5414995 , 0.19642162],
         [0.48716152, 0.53051543, 0.18828416]],

        [[0.08821416, 0.9517412 , 0.8610064 ],
         [0.30999136, 0.29496896, 0.9713614 ],
         [0.11506426, 0.6156452 , 0.07070684]]],


       [[[0.5894662 , 0.67997193, 0.3566662 ],
         [0.06775165, 0.39543378, 0.15745914],
         [0.02828848, 0.0177182 , 0.82267654]],

        [[0.6525562 , 0.40753174, 0.2967404 ],
         [0.7396951 , 0.2978605 , 0.6257639 ],
         [0.2010107 , 0.7105304 , 0.7134371 ]],

        [[0.69556856, 0.69403684, 0.4508797 ],
         [0.67701876, 0.23518848, 0.00815082],
         [0.9044007 , 0.12619221, 0.75219417]]]], dtype=float32)>

In [85]:
rank_4_tensor[:,1:,0,0]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5126076 , 0.08821416],
       [0.6525562 , 0.69556856]], dtype=float32)>

In [79]:
# get various attribute of our tensor
print("datatype of our tensor", rank_4_tensor.dtype)
print("rank/number of dimension of our tensor", rank_4_tensor.ndim)
print("rank/number of dimension of our tensor", tf.rank(rank_4_tensor).numpy())
print("elements of first/0 axis/dimension of our tensor", rank_4_tensor.shape[0])
print("elements of last axis/dimension of our tensor", rank_4_tensor.shape[-1])
print("total number of elements in our tensor", tf.size(rank_4_tensor))
print("total number of elements in our tensor", tf.size(rank_4_tensor).numpy())


datatype of our tensor <dtype: 'float32'>
rank/number of dimension of our tensor 4
rank/number of dimension of our tensor 4
elements of first/0 axis/dimension of our tensor 2
elements of last axis/dimension of our tensor 3
total number of elements in our tensor tf.Tensor(54, shape=(), dtype=int32)
total number of elements in our tensor 54


In [71]:
rank_4_tensor.numpy()

array([[[[0.48962688, 0.5857923 , 0.36451697],
         [0.6550509 , 0.9075084 , 0.37557673],
         [0.6882372 , 0.25384045, 0.49978244]],

        [[0.5126076 , 0.7279091 , 0.58709204],
         [0.9021536 , 0.5414995 , 0.19642162],
         [0.48716152, 0.53051543, 0.18828416]],

        [[0.08821416, 0.9517412 , 0.8610064 ],
         [0.30999136, 0.29496896, 0.9713614 ],
         [0.11506426, 0.6156452 , 0.07070684]]],


       [[[0.5894662 , 0.67997193, 0.3566662 ],
         [0.06775165, 0.39543378, 0.15745914],
         [0.02828848, 0.0177182 , 0.82267654]],

        [[0.6525562 , 0.40753174, 0.2967404 ],
         [0.7396951 , 0.2978605 , 0.6257639 ],
         [0.2010107 , 0.7105304 , 0.7134371 ]],

        [[0.69556856, 0.69403684, 0.4508797 ],
         [0.67701876, 0.23518848, 0.00815082],
         [0.9044007 , 0.12619221, 0.75219417]]]], dtype=float32)

In [72]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0.48962688, 0.5857923 , 0.36451697],
         [0.6550509 , 0.9075084 , 0.37557673],
         [0.6882372 , 0.25384045, 0.49978244]],

        [[0.5126076 , 0.7279091 , 0.58709204],
         [0.9021536 , 0.5414995 , 0.19642162],
         [0.48716152, 0.53051543, 0.18828416]],

        [[0.08821416, 0.9517412 , 0.8610064 ],
         [0.30999136, 0.29496896, 0.9713614 ],
         [0.11506426, 0.6156452 , 0.07070684]]],


       [[[0.5894662 , 0.67997193, 0.3566662 ],
         [0.06775165, 0.39543378, 0.15745914],
         [0.02828848, 0.0177182 , 0.82267654]],

        [[0.6525562 , 0.40753174, 0.2967404 ],
         [0.7396951 , 0.2978605 , 0.6257639 ],
         [0.2010107 , 0.7105304 , 0.7134371 ]],

        [[0.69556856, 0.69403684, 0.4508797 ],
         [0.67701876, 0.23518848, 0.00815082],
         [0.9044007 , 0.12619221, 0.75219417]]]], dtype=float32)>

# indexing tensors(like py list)

In [88]:
# get first two element of each dimension of tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.48962688, 0.5857923 ],
         [0.6550509 , 0.9075084 ]],

        [[0.5126076 , 0.7279091 ],
         [0.9021536 , 0.5414995 ]]],


       [[[0.5894662 , 0.67997193],
         [0.06775165, 0.39543378]],

        [[0.6525562 , 0.40753174],
         [0.7396951 , 0.2978605 ]]]], dtype=float32)>

In [89]:
rank_4_tensor

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0.48962688, 0.5857923 , 0.36451697],
         [0.6550509 , 0.9075084 , 0.37557673],
         [0.6882372 , 0.25384045, 0.49978244]],

        [[0.5126076 , 0.7279091 , 0.58709204],
         [0.9021536 , 0.5414995 , 0.19642162],
         [0.48716152, 0.53051543, 0.18828416]],

        [[0.08821416, 0.9517412 , 0.8610064 ],
         [0.30999136, 0.29496896, 0.9713614 ],
         [0.11506426, 0.6156452 , 0.07070684]]],


       [[[0.5894662 , 0.67997193, 0.3566662 ],
         [0.06775165, 0.39543378, 0.15745914],
         [0.02828848, 0.0177182 , 0.82267654]],

        [[0.6525562 , 0.40753174, 0.2967404 ],
         [0.7396951 , 0.2978605 , 0.6257639 ],
         [0.2010107 , 0.7105304 , 0.7134371 ]],

        [[0.69556856, 0.69403684, 0.4508797 ],
         [0.67701876, 0.23518848, 0.00815082],
         [0.9044007 , 0.12619221, 0.75219417]]]], dtype=float32)>

In [98]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[0,0,0],rank_4_tensor[:1,:1,:1], rank_4_tensor[0,:1,0],rank_4_tensor[:1,:1,:1,:]

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.48962688, 0.5857923 , 0.36451697], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0.48962688, 0.5857923 , 0.36451697]]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.48962688, 0.5857923 , 0.36451697]], dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0.48962688, 0.5857923 , 0.36451697]]]], dtype=float32)>)

In [99]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 3, 1), dtype=float32, numpy=
array([[[[0.48962688],
         [0.6550509 ],
         [0.6882372 ]]]], dtype=float32)>

In [104]:
# Create rank 2 tensor(2 dimension)
rank_2_tensor=tf.constant([[2,3],
                           [4,5]])

In [105]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [106]:
tf.reshape(rank_2_tensor, (4,1,1))

<tf.Tensor: shape=(4, 1, 1), dtype=int32, numpy=
array([[[2]],

       [[3]],

       [[4]],

       [[5]]], dtype=int32)>

In [107]:
tf.reshape(rank_2_tensor, (4,1,1))

<tf.Tensor: shape=(4, 1, 1), dtype=int32, numpy=
array([[[2]],

       [[3]],

       [[4]],

       [[5]]], dtype=int32)>

In [113]:
# get last element of each dimension of rank 2 tensor
rank_2_tensor[-1,-1].numpy()

5

In [111]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [112]:
rank_2_tensor[:-1,:-1].numpy()

array([[2]], dtype=int32)

In [115]:
rank_2_tensor[-1:,-1:].numpy()

array([[5]], dtype=int32)

In [116]:
# get the last item of each row of rank 2 tensor
rank_2_tensor[:,-1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [5]], dtype=int32)>

In [119]:
# reshape tensor adding/removing extra dimension is helpful to alter size of our tensors in tensorflow so that shape line up
tf.reshape(rank_2_tensor, (2,2,1))

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [121]:
# add in extra dimension to our rank to tensor(another way by danial). keep exact info stored in rank 2 tensor
rank_3_tensor=rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [126]:
rank_2_tensor[...]==rank_2_tensor[:, :]

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [127]:
# ... means get all previous axis 

In [128]:
rank_4_tensor=rank_2_tensor[..., tf.newaxis, tf.newaxis ]
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[2]],

        [[3]]],


       [[[4]],

        [[5]]]], dtype=int32)>

In [130]:
# or you can replace ... with number of :,  according to number of rank/dimension
rank_3_tensor=rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [167]:
# alternative to tf.newaxis is tf.expand_dims()
tf.expand_dims(rank_2_tensor, axis=-1) #-1 means expand the final(last) axis/ put -2 or 0 or 1 or 2
# reshape can be used for 2*3 tensor to 3*2 or 6*1 meaning still possessing same number of dimension as original but not with expand_dims and nweaxis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [139]:
# expand second axis/ means last axis here being 2D
tf.expand_dims(rank_2_tensor, axis=2)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

## manipulating tensors (tensor operation)
**Basic operations**
`+`,`-`,`*`, `/`

In [141]:
#  Add values to tensor using addition operator
tensor=tf.constant([[1,2],
                    [3,4]])

In [143]:
tensor+10
# original tensor is unchanged, to change assign with operation

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [150]:
# in addition to python operators, you can use tensorflow function access tensorflow library which do same operation. 
# if you want your code to be sped up on GPU use tenserflow version of operator rather using +, -
# tensorflow built in function
# google tf.math get all functions
tf.multiply(10,tensor), tf.add(tensor, 12)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[13, 14],
        [15, 16]], dtype=int32)>)

In [151]:
tf.math.multiply(10,tensor)# we can use alias of tf.multiply

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [152]:
tf.math.multiply(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [153]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

**Matrix Multiplication**
 >In ML, matrix multiplicatio is of the most common tensor operation. basic operation are element wise like add. matrix and tensor interchangable here and matrix multiplication is taking dot product.
 

In [155]:
tf.linalg.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [157]:
# using only alias
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [161]:
tf.matmul([[1,2],[3,4]], [[5,5],[2,2]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9,  9],
       [23, 23]], dtype=int32)>

In [166]:
# matrix multiplication with python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [170]:
tf.matmul(tensor,tensor, transpose_b=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 11],
       [11, 25]], dtype=int32)>

In [168]:
tf.matmul(tensor,tensor, transpose_a=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

In [173]:
tf.matmul(tf.reshape(tensor, [2,2]), tensor) # if you have 2 tensor 3*2 and 3*2, it is handy to make inner dimension same for matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [174]:
# transpose and reshape gives different outcomes even if for matris 3*2 we transpose to become 2*3 or reshape to become 2*3

In [177]:
tensor, tf.reshape(tensor, (2,2)),tf.transpose(tensor)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4]], dtype=int32)>)

In [176]:
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [178]:
a=tf.random.uniform((2,3))

In [180]:
a,  tf.reshape(a, (3,2)),tf.transpose(a)

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0.42140496, 0.58069193, 0.28269458],
        [0.59165394, 0.533049  , 0.63115454]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.42140496, 0.58069193],
        [0.28269458, 0.59165394],
        [0.533049  , 0.63115454]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.42140496, 0.59165394],
        [0.58069193, 0.533049  ],
        [0.28269458, 0.63115454]], dtype=float32)>)

In [182]:
# transpose flips axis while reshape suffles around element of tensor to makes the tensor into shape you want.

**`tf.tensordot(a,b)`==`tf.matmul(a,b)`==`@`(for python)**

In [193]:
tf.tensordot(tensor,tensor, axes = 1)==tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [194]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [195]:
tf.tensordot(tensor,tensor, axes = 0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 2,  4],
         [ 6,  8]]],


       [[[ 3,  6],
         [ 9, 12]],

        [[ 4,  8],
         [12, 16]]]], dtype=int32)>

## Change tensor dtype

In [197]:
tf.__version__

'2.11.0'

In [211]:
# create tensor with default datatype(default based on data, here float32)
B=tf.constant([1.3,2.4,3.5,4.3])
B.dtype

tf.float32

In [212]:
C=tf.constant([2,3,4,5])
C.dtype

tf.int32

In [213]:
tf.dtypes.cast(C, tf.int16)

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([2, 3, 4, 5], dtype=int16)>

In [214]:
# by using alias
tf.cast(B, dtype=tf.float16)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1.3, 2.4, 3.5, 4.3], dtype=float16)>

In [218]:
# change from float32 to float 16(called reduced precision)
tf.cast(B, dtype=tf.float16)
# for large tensor almost half the memory preserved + performance in modern hardware accelerator like GPU and TPU increases by twice too but low precision.

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1.3, 2.4, 3.5, 4.3], dtype=float16)>

NVIDIA GPUs can run operations in float16 faster than in float32, and TPUs can run operations in bfloat16 faster than float32. Therefore, these lower-precision dtypes should be used whenever possible on those devices. However, variables and a few computations should still be in float32 for numeric reasons so that the model trains to the same quality. The Keras mixed precision API allows you to use a mix of either float16 or bfloat16 with float32, to get the performance benefits from float16/bfloat16 and the numeric stability benefits from float32.
`google tensorflow bit precision`

In [224]:
# change from int32 to float32
E=tf.cast(B, dtype=tf.float32)
E

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.3, 2.4, 3.5, 4.3], dtype=float32)>

In [226]:
E_float16=tf.cast(E, tf.float16)
E_float16

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1.3, 2.4, 3.5, 4.3], dtype=float16)>

## Aggregating tensors
aggtegating tensor==condensing them from multiple of values down to smaller amount of values

In [227]:
# getting the absolute values of tensor
tensor=tf.constant([-1,2,4,-5.5])

In [234]:
list(tf.abs(tensor).numpy())
# shift + command +space to get docsstring

[1.0, 2.0, 4.0, 5.5]

lets go through more aggrigation function


1.   minimum
2.   maximum
3.   sum of tensor
4.   mean of tensor









In [249]:
agg_tensor=tf.constant([[1,2,3],[3,4,1]])
tf.math.reduce_min(agg_tensor, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [250]:
# or use alias
tf.reduce_max(agg_tensor, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 4, 3], dtype=int32)>

In [253]:
tf.reduce_mean(agg_tensor, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 2], dtype=int32)>

In [255]:
tf.reduce_sum(agg_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [256]:
# calculate the large tensor with value between 0 and 100 of size 50
tf.random.uniform((25,2), minval=0, maxval=100)

<tf.Tensor: shape=(25, 2), dtype=float32, numpy=
array([[96.59534  , 70.0438   ],
       [21.7548   ,  6.525898 ],
       [21.781467 , 20.961498 ],
       [72.122284 , 50.428963 ],
       [73.57051  ,  6.668675 ],
       [34.826565 , 26.65646  ],
       [31.096315 , 61.949623 ],
       [50.94631  , 30.490149 ],
       [54.13226  , 91.67947  ],
       [ 6.1190724, 85.84317  ],
       [ 3.5464168, 12.356388 ],
       [31.783688 , 96.47371  ],
       [41.784214 , 88.09492  ],
       [16.108776 , 46.933258 ],
       [22.514856 , 93.230125 ],
       [16.625118 , 20.055258 ],
       [34.088017 , 86.3053   ],
       [86.93222  , 12.523281 ],
       [37.922752 , 53.58341  ],
       [30.825115 , 72.40162  ],
       [56.7315   , 34.02196  ],
       [84.56925  , 36.375153 ],
       [16.96502  , 13.768649 ],
       [ 4.213524 , 65.457115 ],
       [52.464928 , 46.55695  ]], dtype=float32)>

In [261]:
# calculate the large tensor with value between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))

In [262]:
E.ndim, tf.size(E), E.shape, 

(1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [263]:
np.min(E)

4

In [264]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [265]:
# find the variance and standard deviation of our tensor
np.std(E)

25.37732058354467

In [280]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))
# working with tensorflow, float32 is standard type for entire library

<tf.Tensor: shape=(), dtype=float32, numpy=25.37732>

In [277]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=644.0083>

In [278]:
import tensorflow_probability as tfp

In [279]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=644>

## find positional max and min of tensor using axis
# use case when find max of representational output probability

In [302]:
# create new tensor to find positional max and min
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])

In [303]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [304]:
np.argmax(F)

42

In [305]:
tf.argmax(F)
# gives the positional/index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [306]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [307]:
tf.reduce_max(F)==F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [308]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [311]:
tf.reduce_max(F)!=F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=False>

In [313]:
# assert gives error if equal
assert tf.reduce_max(F)!=F[tf.argmax(F)]

AssertionError: ignored

In [314]:
assert True

In [315]:
assert False

AssertionError: ignored

## Squeezing tensors/removing all single dimensions from tensors eg (1,2,1,3) converted to (2,3)

In [334]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [335]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [338]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# one hot encoding=form to encode categorical data into numerical
form of numerical incoding as our model process numbers not string

In [355]:
# create list of indices
some_list=[0, 1,2,3] #could be red, green blue it's categories
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [357]:
tf.one_hot(some_list, depth=3, on_value="present", off_value="absent") # custom value for one hot encode

<tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'present', b'absent', b'absent'],
       [b'absent', b'present', b'absent'],
       [b'absent', b'absent', b'present'],
       [b'absent', b'absent', b'absent']], dtype=object)>

#more math tensorflow

In [358]:
H=tf.range(1,10)

In [361]:
tf.math.square(H) #or alias

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [366]:
tf.math.sqrt(H)#make dtype lab dtype as in error

InvalidArgumentError: ignored

In [367]:
tf.math.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [368]:
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensor and numpy
tensorflow interacts beautifully with numpy arrays

In [372]:
#  create tensor directly from numpy array. tensordflow built upon tensor and numpy built upon array with full interoperability between tensorflow and numpy
J=tf.constant(np.array([1,2,3,4]))
J, type(J)

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>,
 tensorflow.python.framework.ops.EagerTensor)

In [373]:
# convert tensor back to numpy array
np.array(J), type(np.array(J) )

(array([1, 2, 3, 4]), numpy.ndarray)

In [375]:
# convert tensor back to numpy array another method in tensorflow
J.numpy(),  type(J.numpy())
 

(array([1, 2, 3, 4]), numpy.ndarray)

In [377]:
# some functionality we want to use that dont work with data intensive types like tensor we convert to numpy array and viceversa

In [380]:
# default type of each numpy array and tensor slightly different
numpy_J=tf.constant(np.array([1,2,3,4]))
tensor_J=tf.constant([1,2,3,4])
# check datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.int64, tf.int32)

In [381]:
# default type of each numpy array and tensor slightly different
numpy_J=tf.constant(np.array([1.4,2,3,4])) # from numpy array
tensor_J=tf.constant([1,2,3.4,4]) #from python list
# check datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [382]:
np.array([1.4,2,3,4]).dtype

dtype('float64')

In [389]:
# one of main issues with tensors is different datatype issues and if you have converted numpy array to tensor than most of the time you may need to convert to appropriate type like float32 to work with tensorflow

In [391]:
# tensorflow tensor and numpy array difference is tensorflow tensor can be run on GPU and TPU for faster numerical processing

In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
# some GPU from low to high speed Nvidia K80s, T4s,P4, and P100s ===higher the number faster p100 is fastest among them 

In [6]:
!nvidia-smi
# we got access to tesla t4 GPU with almost 16 gigabytes of memory(15360MiB) with CUDA version 11.6

Thu Feb 16 09:20:36 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## CUDA is basically a driver is the interface between GPU and tensorflow code that makes tensorflow code run really fast by parallel.
if you have accessed to CUDA enabled GPU, tensorflow will automatically use it whenever possible
CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs).